#pragma once

#include "DailyInterface.hpp"
#include "decoders/DecoderInterface.hpp"

namespace daily_solver
{
  /**
   * @struct ACOConfigPrevProfit
   * @brief Configuration parameters for the Ant Colony Optimization (ACO) algorithm version
   * that considers previous profit.
   */
  struct ACOConfigPrevProfit
  {
    int num_ants;            /**< Number of ants used in each iteration. */
    double alpha;            /**< Weight of the pheromone trail (importance of past experience). */
    double beta;             /**< Weight of the heuristic information (importance of greedy choice). */
    double q;                /**< Constant used to determine the amount of pheromone deposited. */
    double evaporation_rate; /**< Rate at which pheromones evaporate per iteration (0.0 to 1.0). */
  };

  /**
   * @class ACOPrevProfit
   * @brief Ant Colony Optimization solver for the daily routing and inventory problem
   * that considers previous profit.
   *
   * This class generates daily routes by simulating the behavior of ants finding the
   * shortest paths, guided by pheromone trails and heuristic evaluations, decoded
   * via the provided DecoderInterface.
   */
  class ACOPrevProfit
  {
  private:
    ACOConfigPrevProfit config;
    const routing::DecoderInterface &decoder;

  public:
    /**
     * @brief Constructs the ACOPrevProfit solver.
     *
     * @param config The hyperparameter configuration for the ACO.
     * @param decoder The decoder strategy used to translate ant paths into actual daily routes.
     */
    ACOPrevProfit(ACOConfigPrevProfit config, const routing::DecoderInterface &decoder);

    /**
     * @brief Executes the ACOPrevProfit algorithm for a single day.
     *
     * @param ctx The context (inventory, demand, constraints) for the current day.
     * @param time_limit_seconds Maximum allowed execution time for this daily solve.
     * @return A vector of candidate DailyResult solutions generated by the ants.
     */
    std::vector<DailyResult> solve(const types::DayContext &ctx, double time_limit_seconds) const;
  };
}