#pragma once

#include <vector>
#include <functional>
#include "common/types.hpp"

namespace daily_solver
{
  /**
   * @struct DailyResult
   * @brief Pairs a raw generated sequence with its fully decoded solution.
   *
   * This struct is used by daily solvers to return both the abstract algorithmic
   * representation (like a GA chromosome or an ACO ant path) and the actual
   * evaluated business logic (the decoded routes, times, and inventory).
   */
  struct DailyResult
  {
    std::vector<size_t> sequence; /**< The raw node visitation sequence generated by the algorithm. */
    types::DaySolution solution;  /**< The fully decoded routing and inventory solution. */
  };

  /**
   * @typedef SolverAlgorithm
   * @brief A generic function signature for any daily routing solver.
   *
   * This type alias acts as a universal contract. It allows higher-level
   * multi-period strategies (like Beam Search) to accept any daily solver
   * (such as GA or ACO) as a lambda or callback parameter, completely decoupling
   * the multi-period logic from the specific daily optimization technique.
   *
   * @param ctx The context containing the instance data and current day's starting state.
   * @param time_limit_seconds The maximum execution time allowed for the daily solver.
   * @return A vector of candidate DailyResult solutions.
   */
  using SolverAlgorithm = std::function<std::vector<DailyResult>(
      const types::DayContext &ctx,
      double time_limit_seconds)>;
}