#pragma once

#include <vector>
#include "common/types.hpp"

namespace routing
{

  /**
   * @class DecoderInterface
   * @brief Abstract base class for all sequence decoders.
   *
   * A decoder acts as the bridge between a meta-heuristic algorithm and the actual business
   * logic of the problem. It takes a raw sequence of client IDs and translates it into a
   * concrete, evaluated routing and inventory schedule.
   */
  class DecoderInterface
  {
  public:
    virtual ~DecoderInterface() = default;

    /**
     * @brief Translates an abstract client sequence into a complete daily solution.
     *
     * @param sequence A raw vector of client node IDs generated by a solver (e.g., ACO or GA).
     * @param ctx The current day's context, containing instances, demands, and starting inventory.
     * @return types::DaySolution The fully evaluated routing schedules, inventory tracking, and utility scores.
     */
    virtual types::DaySolution decode(
        const std::vector<size_t> &sequence,
        const types::DayContext &ctx) const = 0;
  };
}