#pragma once

#include <vector>
#include "common/types.hpp"

namespace multi_period
{
  /**
   * @brief Represents a single candidate state (node) in the multi-period search tree.
   *
   * During the Beam Search process, multiple candidate solutions are generated for each day.
   * This struct encapsulates a specific candidate, tracking its lineage to reconstruct the
   * full multi-period path, the raw sequence generated by the daily meta-heuristic (GA/ACO),
   * and the fully evaluated day's solution.
   */
  struct DayNodeSolution
  {
    int node_id;                             /**< Unique identifier for this node in the search tree. */
    int parent_id;                           /**< Identifier of the parent node from the previous day used to trace back the timeline. */
    std::vector<size_t> chromosome_sequence; /**< The raw sequence of clients before decoding. */
    types::DaySolution decoded_solution;     /**< The fully evaluated routing, inventory, and utility data for this day. */

    /**
     * @brief Constructs a new Day Node Solution object.
     *
     * @param id The unique identifier for this node.
     * @param parent The identifier of the parent node from the prior day.
     * @param sequence The raw sequence of clients generated by the daily algorithm.
     * @param solution The fully decoded and evaluated routing solution for this specific day.
     */
    DayNodeSolution(int id, int parent, std::vector<size_t> sequence, types::DaySolution solution)
        : node_id(id), parent_id(parent), chromosome_sequence(std::move(sequence)), decoded_solution(std::move(solution)) {}
  };
}