#pragma once

#include <vector>
#include <deque>
#include "common/types.hpp"
#include "common/instance.hpp"

namespace common
{
  /**
   * @class SolverResult
   * @brief Encapsulates the final solution produced by a routing solver.
   *
   * This class holds the raw daily routes and provides standardized methods
   * to validate constraints, extract global performance metrics (like total profit
   * or missed schedules), and export the results for analysis.
   */
  class SolverResult
  {
  private:
    std::vector<types::DaySolution> solution;
    instance::InstanceSolverFormat instance;
    std::deque<types::DayContext> day_contexts;

    double execution_time_seconds;

    /**
     * @brief Generates the sequence of day contexts based on inventory flow.
     */
    void build_contexts();

  public:
    /**
     * @brief Constructs a new SolverResult object.
     *
     * @param sol The raw vector of day-by-day solutions generated by the solver.
     * @param inst The original problem instance containing demands and capacities.
     * @param exec_time The total time in seconds the solver took to execute.
     */
    SolverResult(const std::vector<types::DaySolution> &sol,
                 const instance::InstanceSolverFormat &inst,
                 double exec_time);

    /**
     * @brief Retrieves the raw solution vector.
     * @return A constant reference to the daily solutions.
     */
    const std::vector<types::DaySolution> &get_solution() const;

    /**
     * @brief Validates the mathematical and logical integrity of the solution.
     *
     * @param verbose If true, prints detailed step-by-step validation checks to standard output.
     * @return true if the solution passes all constraints.
     * @return false if any constraint is violated.
     */
    bool validate(bool verbose = false) const;

    /**
     * @brief Calculates the global profit score across all days.
     * @return The sum of profit from restocked products minus penalties.
     */
    float get_total_profit() const;

    /**
     * @brief Calculates the total amount of products restocked across the entire time horizon.
     * @return Total units restocked.
     */
    int get_total_restocked() const;

    /**
     * @brief Calculates the total accumulated missing inventory across all clients and days.
     * @return Total units of missing product.
     */
    int get_total_missing() const;

    /**
     * @brief Counts the absolute number of client visits made by all workers over all days.
     * @return Total number of visits.
     */
    int get_total_visits() const;

    /**
     * @brief Counts how many client delivery schedules were missed.
     * @return Total number of missed schedules.
     */
    int get_total_missed_schedules() const;

    /**
     * @brief Calculates the average time workers spent on their routes.
     * @return Average working time in seconds.
     */
    int get_avg_working_hours() const;

    /**
     * @brief Prints a high-level metric summary to standard output.
     *
     * If the 'tuning' flag was set to true during construction, this will output
     * a single numerical value (the inverted profit) for automated parsing.
     */
    void print_summary(bool tuning = false) const;
  };
}